const KEY='hcmTrip2026';
const defaults={packing:['여권 유효일 확인','여행자보험 가입','위탁수하물 추가 여부','여행경비 (100달러 또는 5만원권)','트래블월렛 등 카드 비밀번호 및 출금정보','보조배터리','해외유심 또는 e-SIM','비상용 VISA 카드','Grab 앱 설치 및 카드 등록','상비약','세면도구','휴대폰 충전기','샤워필터'],checked:[],foods:['쌀국수','껌땀','피자','코코넛커피','반깐꾸어(게쌀국수)','분짜','짜조','반쎄오','반미'],eaten:[],places:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaults); if(!db.packing.includes('샤워필터')) db.packing.push('샤워필터'); let filter='전체';
function persist(){localStorage.setItem(KEY,JSON.stringify(db))}function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo(0,0);}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function dday(){let n=new Date(),t=new Date('2026-10-17T00:00:00+09:00'),d=Math.ceil((t-n)/86400000);document.getElementById('dday').textContent=d>0?'D-'+d:d===0?'D-DAY':'여행중'}dday();
const days=[['10/17 토 · DAY 1',['09:05 인천공항 T2 출발 · KE471','12:35 떤선녓공항 T2 도착','14:00 Sherwood Residence 체크인']],['10/18 일 · DAY 2',[]],['10/19 월 · DAY 3',[]],['10/20 화 · DAY 4',[]],['10/21 수 · DAY 5',[]],['10/22 목 · DAY 6',[]],['10/23 금 · DAY 7',['12:00 호텔 체크아웃','13:55 떤선녓공항 T2 출발 · KE472','21:25 인천공항 T2 도착']]];document.getElementById('days').innerHTML=days.map(d=>`<div class="day"><h3>${d[0]}</h3>${d[1].length?d[1].map(e=>`<div class="event">${e}</div>`).join(''):'<div class="event">＋ 일정은 다음 버전에서 추가/수정 가능하도록 확장</div>'}</div>`).join('');
function renderPacking(){let box=document.getElementById('packingList');box.innerHTML=db.packing.map((x,i)=>`<label class="check ${db.checked.includes(i)?'done':''}"><input type="checkbox" ${db.checked.includes(i)?'checked':''} onchange="togglePack(${i})"><span>${x}</span></label>`).join('');let n=db.checked.length,p=db.packing.length;document.getElementById('progressText').textContent=`${n} / ${p} 완료`;document.getElementById('progressBar').style.width=(n/p*100)+'%';}function togglePack(i){db.checked=db.checked.includes(i)?db.checked.filter(x=>x!==i):[...db.checked,i];persist();renderPacking()}function toggleFood(i){db.eaten=db.eaten.includes(i)?db.eaten.filter(x=>x!==i):[...db.eaten,i];persist();renderPacking()}renderPacking();
let foodFilter='전체';
function placeCard(p){return `<div class="card"><div class="placeTop"><div><b>${esc(p.name)}</b><p>${esc(p.address||'주소 미입력')}</p></div><span class="badge">${p.category}</span></div>${p.hours?`<p>🕐 ${esc(p.hours)}</p>`:''}${p.memo?`<p>📝 ${esc(p.memo)}</p>`:''}<div class="actions">${p.map?`<button onclick="window.open('${attr(p.map)}','_blank')">🗺 지도</button>`:''}<button onclick="editPlace('${p.id}')">✏️ 수정</button><button onclick="deletePlace('${p.id}')">🗑 삭제</button></div></div>`}
function renderRestaurants(){const q=(document.getElementById('foodSearch')?.value||'').trim().toLowerCase();const list=(window.RESTAURANTS||[]).filter(p=>(foodFilter==='전체'||p.category===foodFilter)&&(!q||[p.name,p.category,p.main,p.recommended,p.memo,p.address].join(' ').toLowerCase().includes(q)));document.getElementById('foodCount').textContent=list.length;document.getElementById('foodPlaceList').innerHTML=list.length?list.map(p=>`<button class="restaurant-card" onclick="openRestaurant('${p.id}')"><div class="restaurant-icon">${p.category==='카페'?'☕':p.category==='디저트'?'🍰':'🍽️'}</div><div class="restaurant-copy"><div class="restaurant-title"><b>${esc(p.name)}</b><span>${esc(p.category)}</span></div><p>${esc(p.main||'-')}</p>${p.recommended&&p.recommended!=='-'?`<small>추천 · ${esc(p.recommended)}</small>`:''}</div><i>›</i></button>`).join(''):'<div class="card"><b>검색 결과가 없습니다.</b><p>검색어나 카테고리를 변경해보세요.</p></div>'}
function openRestaurant(id){const p=(window.RESTAURANTS||[]).find(x=>x.id===id);if(!p)return;rdCategory.textContent=p.category||'';rdName.textContent=p.name||'';rdMain.textContent=p.main||'-';rdRating.textContent=p.rating&&p.rating!=='-'?p.rating:'정보 없음';rdPrice.textContent=p.price&&p.price!=='-'?p.price+' VND':'정보 없음';rdHours.textContent=p.hours&&p.hours!=='-'?p.hours:'정보 없음';rdRecommended.textContent=p.recommended&&p.recommended!=='-'?p.recommended:'정보 없음';rdAddress.textContent=p.address||'정보 없음';rdMemo.textContent=p.memo||'';rdMemoWrap.style.display=p.memo?'flex':'none';rdMap.onclick=()=>window.open(p.map,'_blank');rdMap.disabled=!p.map;restaurantDialog.showModal()}
document.querySelectorAll('[data-food-filter]').forEach(b=>b.onclick=()=>{foodFilter=b.dataset.foodFilter;document.querySelectorAll('[data-food-filter]').forEach(x=>x.classList.toggle('active',x===b));renderRestaurants()});
function renderPlaces(){const empty='<div class="card"><b>아직 등록된 장소가 없습니다.</b></div>';let shop=db.places.filter(p=>p.category==='쇼핑');let tour=db.places.filter(p=>p.category==='관광');document.getElementById('shoppingList').innerHTML=shop.length?shop.map(placeCard).join(''):empty;let base=tours.map(x=>`<div class="card tour-card"><div class="tour-main"><div class="tour-copy"><b>${esc(x.name)}</b><p>${esc(x.address||'')}</p><div class="travel-meta"><span>📍 ${esc(x.distance||'거리 확인')}</span><span>🚕 ${esc(x.taxi||'교통상황에 따라 변동')}</span></div></div>${x.image?`<div class="tour-thumb-wrap"><img class="tour-thumb" src="${attr(x.image)}" alt="${esc(x.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="tour-thumb-fallback">🏙️<span>${esc(x.name)}</span><small>사진 불러오기 실패</small></div></div>`:''}</div>${x.memo?`<p>📝 ${esc(x.memo)}</p>`:''}<div class="actions"><button onclick="window.open('${attr(x.map)}','_blank')">📍 장소</button><button onclick="openRoute('${attr(x.name)}')">🚕 숙소에서 길찾기</button></div></div>`).join('');document.getElementById('tourismList').innerHTML=base+(tour.length?tour.map(placeCard).join(''):'')}
function openPlaceForm(category='쇼핑'){placeForm.reset();placeId.value='';pCategory.value=category;formTitle.textContent='장소 추가';placeDialog.showModal()}function editPlace(id){let p=db.places.find(x=>x.id===id);placeId.value=p.id;pName.value=p.name;pCategory.value=p.category;pAddress.value=p.address;pHours.value=p.hours;pMap.value=p.map;pMemo.value=p.memo;formTitle.textContent='장소 수정';placeDialog.showModal()}function savePlace(){if(!pName.value.trim())return alert('이름을 입력해주세요.');let p={id:placeId.value||crypto.randomUUID(),name:pName.value.trim(),category:pCategory.value,address:pAddress.value.trim(),hours:pHours.value.trim(),map:pMap.value.trim(),memo:pMemo.value.trim()};let i=db.places.findIndex(x=>x.id===p.id);i<0?db.places.push(p):db.places[i]=p;persist();renderPlaces();placeDialog.close()}function deletePlace(id){if(confirm('이 장소를 삭제할까요?')){db.places=db.places.filter(x=>x.id!==id);persist();renderPlaces()}}function esc(s=''){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s=''){return String(s??'').replace(/'/g,'%27')}
const tours=[
{name:'벤탄시장',address:'Bến Thành, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Ben+Thanh+Market&query_place_id=ChIJTeYpMT8vdTERMH8sUnkta40',distance:'약 2.0 km',taxi:'약 7–12분',lat:10.7725,lng:106.69805},
{name:'사이공스퀘어',address:'77–89 Nam Kỳ Khởi Nghĩa, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Square&query_place_id=ChIJU4Nmq0AvdTERUijlxbVwFQQ',distance:'약 2.5 km',taxi:'약 8–13분',lat:10.77363,lng:106.69959},
{name:'응웬후에 광장',address:'Nguyễn Huệ, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Nguyen+Hue+Walking+Street&query_place_id=ChIJd6g1QgAvdTERe3onVtPoGVU',distance:'약 2.2 km',taxi:'약 8–13분',lat:10.77435,lng:106.70368},
{name:'인민위원회 청사 (호치민 시청)',address:'86 Lê Thánh Tôn, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Ho+Chi+Minh+City+People%27s+Committee&query_place_id=ChIJ1cr3QQAvdTERRPfxhUJt7Oo',distance:'약 1.2 km',taxi:'약 5–10분',lat:10.77652,lng:106.70088},
{name:'나이트시티 버스투어',address:'출발: 92–96 Nguyễn Huệ Street',map:'https://www.google.com/maps/d/edit?mid=1v4a4P_58-1P0A2EmnykTq1zKNtWRgBE&usp=sharing',memo:'오픈탑 2층 버스 야간 시티투어 · 공식 Night Tour 지도',distance:'약 2.2 km',taxi:'약 8–13분',lat:10.7748,lng:106.7034},
{name:'부이비엔 여행자 거리',address:'Bùi Viện, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Bui+Vien+Walking+Street&query_place_id=ChIJCdzLBRYvdTERpsMyNScNwPE',distance:'약 3.5 km',taxi:'약 10–18분',lat:10.76719,lng:106.69398},
{name:'롯데마트',address:'469 Nguyễn Hữu Thọ, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Lotte+Mart+District+7&query_place_id=ChIJuf9TI58vdTERe86UdaSdtGo',distance:'약 7 km',taxi:'약 20–30분',lat:10.7417,lng:106.7025},
{name:'무이네 해변',address:'Đ. Xuân Thủy, Mũi Né',map:'https://www.google.com/maps/search/?api=1&query=Mui+Ne+Beach&query_place_id=ChIJhRkJjZaPdjERYEJeFUTK3aU',distance:'약 200 km',taxi:'차량 약 3–4시간',lat:10.941,lng:108.287},
{name:'무이네 모래언덕',address:'Red Sand Dunes · 01 Hòn Rơm, ĐT716, Mũi Né',map:'https://www.google.com/maps/search/?api=1&query=Red+Sand+Dunes+Mui+Ne&query_place_id=ChIJG0sCU6yPdjERGKRMrcgkOxU',distance:'약 205 km',taxi:'차량 약 3–4시간',lat:10.9489,lng:108.2955},
{name:'레탄톤 일본인거리',address:'Saigon Japan Town · 8A Thái Văn Lung, District 1, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Japan+Town&query_place_id=ChIJZXI8z0gvdTERMj9clBCmu9M',memo:'Lê Thánh Tôn 15B · Thái Văn Lung 일대 일본인 거리',distance:'약 2.3 km',taxi:'약 8–13분',lat:10.78162,lng:106.70446},
{name:'떤딘 성당',address:'289 Hai Bà Trưng, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Tan+Dinh+Church&query_place_id=ChIJZ_ShIDMvdTERgrkibFMAu3g',distance:'약 1.0 km',taxi:'약 5–8분',lat:10.78809,lng:106.69076},
{name:'호치민 북 스트리트',address:'2 Nguyễn Văn Bình, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Book+Street&query_place_id=ChIJS8Yv1zcvdTERUI2V47UxkPw',distance:'약 1.5 km',taxi:'약 6–10분',lat:10.78012,lng:106.70095},
{name:'사이공 중앙우체국',address:'02 Công trường Công xã Paris, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Central+Post+Office&query_place_id=ChIJRxocgI4udTERspsje3PV-LA',distance:'약 1.0 km',taxi:'약 5–9분',lat:10.77985,lng:106.69995},
{name:'노트르담 성당',address:'01 Công trường Công xã Paris, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Notre+Dame+Cathedral+of+Saigon&query_place_id=ChIJUSTY5jcvdTERRVvtbJNZT-g',distance:'약 0.8 km',taxi:'약 4–8분',lat:10.77978,lng:106.69902},
{name:'전쟁박물관',address:'28 Võ Văn Tần, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=War+Remnants+Museum&query_place_id=ChIJzwg3ojAvdTERqnQUK99K2Xw',distance:'약 0.5 km',taxi:'약 3–6분',lat:10.77948,lng:106.69203},
{name:'통일궁',address:'135 Nam Kỳ Khởi Nghĩa, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Independence+Palace&query_place_id=ChIJL0dwVTgvdTERao3t8B1Jhxc',distance:'약 0.8 km',taxi:'약 4–8분',lat:10.77714,lng:106.69531},
{name:'오페라 하우스',address:'07 Công trường Lam Sơn, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Opera+House&query_place_id=ChIJKcrnSUYvdTERO64MErYx9VU',distance:'약 2.2 km',taxi:'약 8–13분',lat:10.77648,lng:106.70306},
{name:'랜드마크 81',address:'720A Điện Biên Phủ, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Landmark+81&query_place_id=ChIJEQnz-MIndTERzRrJ-HNQrDY',distance:'약 5 km',taxi:'약 15–25분',lat:10.79505,lng:106.72193},
{name:'카페 아파트먼트',address:'42 Nguyễn Huệ, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=The+Cafe+Apartment&query_place_id=ChIJP4LyNAAvdTERp2XLe0QvLeU',distance:'약 2.2 km',taxi:'약 8–13분',lat:10.77422,lng:106.70333},
{name:'호치민 배 투어 (Bến tàu Bạch Đằng)',address:'10B Tôn Đức Thắng, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Bach+Dang+Speed+Ferry+Terminal&query_place_id=ChIJ1fMOPUQvdTERT8UeUWg0Ug8',memo:'Bạch Đằng 선착장 기준',distance:'약 2.8 km',taxi:'약 10–15분',lat:10.77362,lng:106.70686},
{name:'담센 문화공원 (워터파크)',address:'3 Hòa Bình, Bình Thới, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Dam+Sen+Water+Park&query_place_id=ChIJ4RqUkJkudTER-QHI35eZcWI',memo:'Đầm Sen Water Park · 워터파크/놀이시설',distance:'약 7.3 km',taxi:'약 20–30분',lat:10.7663,lng:106.6374},
{name:'사이공 스카이덱',address:'49F Bitexco Financial Tower · 36 Hồ Tùng Mậu, Ho Chi Minh City',map:'https://www.google.com/maps/search/?api=1&query=Saigon+Skydeck&query_place_id=ChIJVZKCP0EvdTERfHvs6AfGjok',memo:'Bitexco Financial Tower 49층 · 360° 전망대',distance:'약 2.7 km',taxi:'약 10–15분',lat:10.77192,lng:106.70445}
];const TOUR_IMAGES={"벤탄시장": "assets/tourism/ben-thanh.png", "사이공스퀘어": "assets/tourism/saigon-square.png", "응웬후에 광장": "https://i0.wp.com/caffeinatedexcursions.com/wp-content/uploads/2019/12/IMG_20191102_182923.jpg?fit=1200%2C900&ssl=1", "인민위원회 청사 (호치민 시청)": "https://media.cntraveller.com/photos/611bf55580db5ca184e71624/4:3/w_572,h_429,c_limit/hochiminhcity_cnt_9nov09_istock_b.jpg", "나이트시티 버스투어": "https://divui.com/content/images/thumbs/0030102_bus-2-tang-hop-on-hop-off-ho-chi-minh.jpeg", "부이비엔 여행자 거리": "https://i.pinimg.com/originals/94/06/5f/94065f9d6b18d135e7b979100657de01.jpg", "롯데마트": "assets/tourism/lotte-mart.png", "무이네 해변": "assets/tourism/mui-ne-beach.png", "무이네 모래언덕": "assets/tourism/mui-ne-dunes.png", "레탄톤 일본인거리": "https://danviet.ex-cdn.com/files/f1/296231569849192448/2024/10/14/img5863-1728911313275272086605.jpeg", "떤딘 성당": "assets/tourism/tan-dinh.png", "호치민 북 스트리트": "https://app-api.glodival.vn/storage/4/images/ho-chi-minh-city-book-street-1767947106ojtwZ.jpg", "사이공 중앙우체국": "assets/tourism/central-post-office.png", "노트르담 성당": "https://lp-cms-production.imgix.net/2024-03/shutterstockRF300914393.jpg?auto=format%2Ccompress&crop=faces%2Cedges&fit=crop&h=821&q=72&w=1095", "전쟁박물관": "assets/tourism/war-remnants.png", "통일궁": "https://images2.thanhnien.vn/zoom/1200_630/528068263637045248/2023/12/31/h5-17040272598292064926495-137-0-765-1200-crop-1704027467375556338406.jpg", "오페라 하우스": "https://evivatour.com/wp-content/uploads/2021/09/Saigon-Opera-House-1-1000x565.jpg", "랜드마크 81": "https://www.viet-jo.com/image/news/180804031658.jpg", "카페 아파트먼트": "assets/tourism/cafe-apartment.png", "호치민 배 투어 (Bến tàu Bạch Đằng)": "https://images2.thanhnien.vn/528068263637045248/2025/1/16/2buyt-173701075359645860562.jpg", "담센 문화공원 (워터파크)": "https://img1.advisor.travel/1200x630px-Dam_Sen_Park_16.jpg", "사이공 스카이덱": "assets/tourism/saigon-skydeck.png"};tours.forEach(t=>t.image=TOUR_IMAGES[t.name]||"");const HOTEL={lat:10.78255,lng:106.69185};
function openRoute(name){window.open('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent('Sherwood Residence, 127 Pasteur, Ho Chi Minh City')+'&destination='+encodeURIComponent(name+', Ho Chi Minh City')+'&travelmode=driving','_blank')}
const TOUR_LIST_KEY='hcmTourGoogleListUrl';
function saveTourGoogleList(){const el=document.getElementById('tourGoogleListUrl');const u=(el?.value||'').trim();if(!u){alert('Google Maps 공유 목록 링크를 붙여넣어 주세요.');return}if(!/^https?:\/\//i.test(u)){alert('https:// 로 시작하는 Google Maps 공유 링크를 입력해 주세요.');return}localStorage.setItem(TOUR_LIST_KEY,u);alert('관광지 Google Maps 목록 링크를 저장했습니다.');}
function openTourGoogleList(){const u=localStorage.getItem(TOUR_LIST_KEY);if(u){window.open(u,'_blank');return}showGoogleListHelp();}
function showGoogleListHelp(){alert('Google Maps에서 새 목록을 만든 뒤 앱에 등록한 관광지만 저장하세요.\n\nGoogle Maps → 저장됨/나 → 새 목록 → 장소 저장 → 목록 공유 → 링크 복사\n\n복사한 링크를 이 화면의 입력칸에 붙여넣고 저장하면 됩니다.');}
function initTourGoogleList(){const el=document.getElementById('tourGoogleListUrl');if(el)el.value=localStorage.getItem(TOUR_LIST_KEY)||'';}
renderPlaces();renderRestaurants();initTourGoogleList();
function openHotelMap(){window.open('https://www.google.com/maps/search/?api=1&query=Sherwood+Residence+127+Pasteur+Ho+Chi+Minh+City','_blank')}
function openCoopMap(){window.open('https://www.google.com/maps/place/Coopmart+Nguyen+Dinh+Chieu/@10.781655,106.6882704,17z/data=!4m15!1m8!3m7!1s0x31752f3ac5d26bcb:0x10bbc4cc0d945d36!2zMTY4IMSQxrDhu51uZyBOZ3V54buFbiDEkMOsbmggQ2hp4buDdSwgWHXDom4gSMOyYSwgSOG7kyBDaMOtIE1pbmgsIOuyoO2KuOuCqA!3b1!8m2!3d10.7771335!4d106.6889892!16s%2Fg%2F11tsgzy2d4!3m5!1s0x31752f31200920bd:0x987d7568197ad8ab!8m2!3d10.7814923!4d106.6924141!16s%2Fg%2F1thnl88q?entry=ttu&g_ep=EgoyMDI2MDkyMy4wIKXMDSoASAFQAw%3D%3D','_blank')}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='HCM_TRIP_2026_backup.json';a.click();URL.revokeObjectURL(a.href)}function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);persist();renderPacking();renderPlaces();renderRestaurants();alert('복원했습니다.')}catch{alert('올바른 백업 파일이 아닙니다.')}};r.readAsText(f)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');

// v0.8.1 shopping & massage
let shopTab='벤탄시장';
function shoppingEmoji(x){if(x.source==='약국')return '💊';if(/커피|차|아이스티/.test(x.name))return '☕';if(/과자|젤리|쿠키|크래커|초콜/.test(x.name))return '🍪';if(/망고|오렌지|코코넛/.test(x.name))return '🥭';if(/셔츠|티|바지|양말|카라/.test(x.name))return '👕';if(/백팩/.test(x.name))return '🎒';return '🛍️'}
function renderShoppingDB(){const box=document.getElementById('shoppingList');if(!box)return;if(shopTab==='마사지'){box.innerHTML=(window.MASSAGES||[]).map(x=>`<div class="massage-card"><b>💆 ${esc(x.name)}</b><p>📍 ${esc(x.address)}</p><button onclick="window.open('${attr(x.map)}','_blank')">📍 GOOGLE MAPS</button></div>`).join('');return;}const list=(window.SHOPPING||[]).filter(x=>x.source===shopTab);let note=shopTab==='벤탄시장'?'<div class="market-note"><b>⚠️ 벤탄시장 쇼핑 메모</b><br>소매치기·가격 바꿔치기 주의 · 음식 위생 확인 · 제시가에서 충분히 흥정 후 구매. 아래 시세는 참고용이며 현장 가격은 달라질 수 있습니다.</div>':shopTab==='약국'?'<div class="pharm-note">💊 의약품은 제품명·성분·용량·사용법을 현지 약사에게 확인하고 구매하세요.</div>':'';box.innerHTML=`<div class="shop-grid">${note}${list.map(x=>`<div class="shop-item"><div class="shop-pic">${x.image?`<img src="${attr(x.image)}" alt="${esc(x.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><div class="shop-fallback" style="display:none">${shoppingEmoji(x)}<small>${esc(x.name)}</small></div>`:`<div class="shop-fallback">${shoppingEmoji(x)}<small>${esc(x.name)}</small></div>`}</div><div class="shop-copy"><b>${esc(x.name)}</b><span>${esc(x.source)}</span>${x.detail?`<p>${shopTab==='벤탄시장'?'💰':'분류 ·'} ${esc(x.detail)}</p>`:''}${x.memo?`<p>📝 ${esc(x.memo)}</p>`:''}</div></div>`).join('')}</div>`}
document.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{shopTab=b.dataset.shopTab;document.querySelectorAll('[data-shop-tab]').forEach(x=>x.classList.toggle('active',x===b));renderShoppingDB()});
const _oldRenderPlaces=renderPlaces;renderPlaces=function(){_oldRenderPlaces();renderShoppingDB()};
setTimeout(renderShoppingDB,0);
