(()=>{'use strict';
const $=id=>document.getElementById(id);const store=(key,obj)=>{try{localStorage.setItem(key,JSON.stringify(obj))}catch(e){}};const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){return null}};
const format=(n)=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:0});
async function getJSON(url){const ctl=new AbortController();const timeout=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(url,{cache:'no-store',signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timeout)}}
function icon(code){if(code===0)return ['☀️','맑음'];if([1,2].includes(code))return ['🌤️','대체로 맑음'];if(code===3)return ['☁️','흐림'];if([45,48].includes(code))return ['🌫️','안개'];if([51,53,55,56,57].includes(code))return ['🌦️','이슬비'];if([61,63,65,66,67,80,81,82].includes(code))return ['🌧️','비'];if([95,96,99].includes(code))return ['⛈️','뇌우'];return ['🌥️','변동'];}
function showWeather(data,air,old){const d=data.daily;if(!d||!Array.isArray(d.time)||d.time.length<7)throw Error('일별 예보 형식 오류');$('weatherDays').innerHTML=d.time.slice(0,7).map((date,i)=>{const [emoji,name]=icon(d.weather_code?.[i]);const day=i===0?'오늘':new Intl.DateTimeFormat('ko-KR',{weekday:'short',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(date+'T12:00:00+07:00'));return `<div class="weather-day"><b>${day}</b><div>${date.slice(5)}</div><span class="wx-icon">${emoji}</span><div>${name}</div><div class="wx-temp">${Math.round(d.temperature_2m_min[i])}° / ${Math.round(d.temperature_2m_max[i])}°</div><div class="wx-rain">☔ ${d.precipitation_probability_max?.[i]??'—'}%</div></div>`}).join('');let c=air?.current;$('weatherAir').textContent=c?`🌫️ 현재 대기질 · PM2.5 ${c.pm2_5??'—'}㎍/㎥ · PM10 ${c.pm10??'—'}㎍/㎥ · 미국 AQI ${c.us_aqi??'—'} (추정치)`:'대기질 정보는 현재 조회할 수 없습니다.';$('weatherStatus').textContent=(old?'⚠️ 저장된 이전 예보 · ':'')+'조회 시각: '+(data._savedAt||new Date().toLocaleString('ko-KR'))+(old?' · 최신 예보 아님':'');}
async function weather(){if(!$('weatherDays'))return;$('weatherStatus').textContent='최신 날씨 조회 중...';try{const [w,a]=await Promise.allSettled([getJSON('https://api.open-meteo.com/v1/forecast?latitude=10.8231&longitude=106.6297&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FHo_Chi_Minh&forecast_days=7'),getJSON('https://air-quality-api.open-meteo.com/v1/air-quality?latitude=10.8231&longitude=106.6297&current=pm2_5,pm10,us_aqi&timezone=Asia%2FHo_Chi_Minh')]);if(w.status!=='fulfilled')throw w.reason;const data=w.value;data._savedAt=new Date().toLocaleString('ko-KR');const air=a.status==='fulfilled'?a.value:null;showWeather(data,air,false);store('hcm-weather-v0911',{data,air})}catch(e){const cached=read('hcm-weather-v0911');if(cached)showWeather(cached.data,cached.air,true);else{$('weatherStatus').textContent='날씨를 가져오지 못했습니다. 인터넷 연결 후 새로고침해 주세요.';$('weatherDays').textContent='';$('weatherAir').textContent='';}}}
let base='KRW',rate=null;function calc(){if(!$('fxResult'))return;const n=Number($('fxAmount').value);$('fxUnit').textContent=base;if(!Number.isFinite(n)||n<0){$('fxResult').textContent='올바른 금액을 입력하세요';return}if(!(rate>0)){$('fxResult').textContent='환율을 조회할 수 없습니다';return}const v=base==='KRW'?n*rate:n/rate;$('fxResult').textContent=format(v)+(base==='KRW'?' ₫':' 원');}
async function fx(){if(!$('fxStatus'))return;$('fxStatus').textContent='환율 갱신 중...';try{const d=await getJSON('https://api.frankfurter.dev/v2/rate/KRW/VND');if(!(Number(d.rate)>0))throw Error('invalid rate');rate=Number(d.rate);store('hcm-fx-v0911',{rate,date:d.date});$('fxStatus').textContent=`기준: 1 KRW = ${rate.toFixed(4)} VND · 발표일 ${d.date} · Frankfurter`;calc()}catch(e){const c=read('hcm-fx-v0911');rate=c?.rate||null;$('fxStatus').textContent=c?`⚠️ 저장된 과거 환율 (${c.date}) · 최신 환율 아님`:'환율 조회 실패 · 인터넷 연결 후 다시 시도하세요';calc()}}
function init(){if(!$('weatherDays')||!$('fxAmount'))return;$('weatherRefresh').addEventListener('click',weather);$('fxRefresh').addEventListener('click',fx);$('fxAmount').addEventListener('input',calc);document.querySelectorAll('[data-fx]').forEach(b=>b.addEventListener('click',()=>{base=b.dataset.fx;document.querySelectorAll('[data-fx]').forEach(x=>x.classList.toggle('active',x===b));$('fxAmount').value=base==='KRW'?'100000':'1000000';calc()}));weather();fx();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();